//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RepositoryPattern.Models.BooksEntity
{
    public partial class BooksTable
    {
        public string Title { get; set; }
        public string Author { get; set; }
        public string Category { get; set; }
        public string Series { get; set; }
        public System.Guid ID { get; set; }
    }
    
}
